#ifndef	QUICKLOOTRE_VERSION_INCLUDED
#define QUICKLOOTRE_VERSION_INCLUDED

#define QUICKLOOTRE_VERSION_MAJOR		1
#define QUICKLOOTRE_VERSION_MINOR		11
#define QUICKLOOTRE_VERSION_PATCH		2
#define QUICKLOOTRE_VERSION_BETA		2
#define QUICKLOOTRE_VERSION_VERSTRING	"1, 11, 2, 2"

#endif
