#ifndef	QUICKLOOTRE_VERSION_INCLUDED
#define QUICKLOOTRE_VERSION_INCLUDED

#define QUICKLOOTRE_VERSION_MAJOR		1
#define QUICKLOOTRE_VERSION_MINOR		12
#define QUICKLOOTRE_VERSION_PATCH		2
#define QUICKLOOTRE_VERSION_BETA		0
#define QUICKLOOTRE_VERSION_VERSTRING	"1, 12, 2, 0"

#endif
