#ifndef	QUICKLOOTRE_VERSION_INCLUDED
#define QUICKLOOTRE_VERSION_INCLUDED

#define QUICKLOOTRE_MAKE_STR_HELPER(x) #x
#define QUICKLOOTRE_MAKE_STR(x) QUICKLOOTRE_MAKE_STR_HELPER(x)

#define QUICKLOOTRE_VERSION_MAJOR		1
#define QUICKLOOTRE_VERSION_MINOR		15
#define QUICKLOOTRE_VERSION_PATCH		4
#define QUICKLOOTRE_VERSION_BETA		0
#define QUICKLOOTRE_VERSION_VERSTRING	QUICKLOOTRE_MAKE_STR(QUICKLOOTRE_VERSION_MAJOR) "." QUICKLOOTRE_MAKE_STR(QUICKLOOTRE_VERSION_MINOR) "." QUICKLOOTRE_MAKE_STR(QUICKLOOTRE_VERSION_PATCH) "." QUICKLOOTRE_MAKE_STR(QUICKLOOTRE_VERSION_BETA)

#endif
