set(headers ${headers}
	include/AutoTOML.hpp
	src/ContainerChangedHandler.h
	src/Hooks.h
	src/HUDManager.h
	src/Loot.h
	src/OpenCloseHandler.h
	src/PCH.h
	src/Settings.h
	src/ViewHandler.h
	src/Animation/Animation.h
	src/CLIK/Array.h
	src/CLIK/MovieClip.h
	src/CLIK/Object.h
	src/CLIK/TextField.h
	src/CLIK/GFx/Controls/Button.h
	src/CLIK/GFx/Controls/ButtonBar.h
	src/CLIK/GFx/Controls/CoreList.h
	src/CLIK/GFx/Controls/DropdownMenu.h
	src/CLIK/GFx/Controls/ScrollingList.h
	src/CLIK/GFx/Controls/Slider.h
	src/CLIK/GFx/Controls/TextInput.h
	src/CLIK/GFx/Core/UIComponent.h
	src/Events/Events.h
	src/Input/Input.h
	src/Input/InputDisablers.h
	src/Input/InputListeners.h
	src/Items/GFxItem.h
	src/Items/GroundItems.h
	src/Items/InventoryItem.h
	src/Items/Item.h
	src/Scaleform/LootMenu.h
	src/Scaleform/Scaleform.h
)
