set(SOURCE_FILES
	${ROOT_DIR}/src/c++/Animation/Animation.h
	${ROOT_DIR}/src/c++/CLIK/Array.h
	${ROOT_DIR}/src/c++/CLIK/GFx/Controls/Button.h
	${ROOT_DIR}/src/c++/CLIK/GFx/Controls/ButtonBar.h
	${ROOT_DIR}/src/c++/CLIK/GFx/Controls/CoreList.h
	${ROOT_DIR}/src/c++/CLIK/GFx/Controls/DropdownMenu.h
	${ROOT_DIR}/src/c++/CLIK/GFx/Controls/ScrollingList.h
	${ROOT_DIR}/src/c++/CLIK/GFx/Controls/Slider.h
	${ROOT_DIR}/src/c++/CLIK/GFx/Controls/TextInput.h
	${ROOT_DIR}/src/c++/CLIK/GFx/Core/UIComponent.h
	${ROOT_DIR}/src/c++/CLIK/MovieClip.h
	${ROOT_DIR}/src/c++/CLIK/Object.h
	${ROOT_DIR}/src/c++/CLIK/TextField.h
	${ROOT_DIR}/src/c++/ContainerChangedHandler.cpp
	${ROOT_DIR}/src/c++/ContainerChangedHandler.h
	${ROOT_DIR}/src/c++/Events/Events.cpp
	${ROOT_DIR}/src/c++/Events/Events.h
	${ROOT_DIR}/src/c++/HUDManager.h
	${ROOT_DIR}/src/c++/Hooks.cpp
	${ROOT_DIR}/src/c++/Hooks.h
	${ROOT_DIR}/src/c++/Input/Input.h
	${ROOT_DIR}/src/c++/Input/InputDisablers.h
	${ROOT_DIR}/src/c++/Input/InputListeners.cpp
	${ROOT_DIR}/src/c++/Input/InputListeners.h
	${ROOT_DIR}/src/c++/Items/GFxItem.h
	${ROOT_DIR}/src/c++/Items/GroundItems.h
	${ROOT_DIR}/src/c++/Items/InventoryItem.h
	${ROOT_DIR}/src/c++/Items/Item.h
	${ROOT_DIR}/src/c++/Loot.cpp
	${ROOT_DIR}/src/c++/Loot.h
	${ROOT_DIR}/src/c++/OpenCloseHandler.h
	${ROOT_DIR}/src/c++/PCH.cpp
	${ROOT_DIR}/src/c++/PCH.h
	${ROOT_DIR}/src/c++/Scaleform/LootMenu.cpp
	${ROOT_DIR}/src/c++/Scaleform/LootMenu.h
	${ROOT_DIR}/src/c++/Scaleform/Scaleform.cpp
	${ROOT_DIR}/src/c++/Scaleform/Scaleform.h
	${ROOT_DIR}/src/c++/Settings.h
	${ROOT_DIR}/src/c++/ViewHandler.cpp
	${ROOT_DIR}/src/c++/ViewHandler.h
	${ROOT_DIR}/src/c++/main.cpp
)
