set(SOURCES
	src/Animation/Animation.h
	src/CLIK/Array.h
	src/CLIK/GFx/Controls/Button.h
	src/CLIK/GFx/Controls/ButtonBar.h
	src/CLIK/GFx/Controls/CoreList.h
	src/CLIK/GFx/Controls/DropdownMenu.h
	src/CLIK/GFx/Controls/ScrollingList.h
	src/CLIK/GFx/Controls/Slider.h
	src/CLIK/GFx/Controls/TextInput.h
	src/CLIK/GFx/Core/UIComponent.h
	src/CLIK/MovieClip.h
	src/CLIK/Object.h
	src/CLIK/TextField.h
	src/ContainerChangedHandler.cpp
	src/ContainerChangedHandler.h
	src/Events/Events.cpp
	src/Events/Events.h
	src/HUDManager.h
	src/Hooks.cpp
	src/Hooks.h
	src/Input/Input.h
	src/Input/InputDisablers.h
	src/Input/InputListeners.cpp
	src/Input/InputListeners.h
	src/Items/GFxItem.h
	src/Items/GroundItems.h
	src/Items/InventoryItem.h
	src/Items/Item.h
	src/Loot.cpp
	src/Loot.h
	src/OpenCloseHandler.h
	src/PCH.cpp
	src/PCH.h
	src/Scaleform/LootMenu.cpp
	src/Scaleform/LootMenu.h
	src/Scaleform/Scaleform.cpp
	src/Scaleform/Scaleform.h
	src/Settings.h
	src/ViewHandler.cpp
	src/ViewHandler.h
	src/main.cpp
)
